# Generated by Django 4.2.1 on 2023-05-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(null=True, upload_to="book_images/"),
        ),
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=200),
        ),
    ]
